import "./feature.css";
import search from "../../assets/features/search.png"
import select from "../../assets/features/select.png"
import standout from "../../assets/features/standout.png"
function Feature() {
  return (
    <div className = "main">
      <div className="mainelement">
        <div className="box">
            <img src = {search}/>
            <h5>Search</h5>
            <p>Simply add a keyword or a term related to your business 
            in the slogan maker search box. Wait for the magic to happen.</p>
        </div>
        <div className = "box">
            <img src = {select}/>
            <h5>Select</h5>
            <p>Choose from thousands of options generated by the slogan 
            maker that fit your needs.</p>
        </div>
        <div className = "box">
            <img src = {standout}/>
            <h5>Stand out</h5>
            <p>Congrats on your new slogan. It's time to win the world!</p>
        </div>
      </div>
    </div>
  );
}

export default Feature;